### ISSUE TITLE
gtmOnFailure should be called in the onFailure handler.

### ISSUE THREAD

**Issue by semisight** [anujtenani/gtm-goaffpro-template#1]
https://github.com/anujtenani/gtm-goaffpro-template/blob/0e5aec6eb372dbd88f29d43e6cb43bd765b77ff6/template.tpl#L104

Scripts should call either `gtmOnSuccess` or `gtmOnFailure` exactly once, any time the script is run.

Not calling this will lead to issues with tag sequencing.

**Comment by anujtenani** [comment]
Thanks. 

Fixed in commit 
https://github.com/anujtenani/gtm-goaffpro-template/commit/cedecfe29cbcb45350d0aab57c95bd2393276ea3
